site_name: My Data
site_url: https://romovpa.github.io/my-data/
site_description: Personal data discovery and analysis

repo_url: https://github.com/romovpa/my-data
repo_name: romovpa/my-data
edit_uri: edit/main/docs/

nav:
  - Home: index.md

theme:
  name: material
  features:
    - content.tooltips
    - content.action.edit
    #- content.action.view
    - content.code.annotate
    - content.code.copy
    #- navigation.tabs
    - navigation.tracking
    - navigation.instant
    - navigation.indexes
    - navigation.selections
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
    #- navigation.footer
    - header.autohide
  icon:
    logo: fontawesome/solid/vault
    repo: fontawesome/brands/git-alt
  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to system preference

plugins:
  - glightbox
  - git-committers:
      repository: romovpa/my-data
      branch: main
  - git-revision-date-localized:
      exclude:
        - index.md
      fallback_to_build_date: true

markdown_extensions:
  - attr_list
  - md_in_html
  - admonition
  - pymdownx.details
  - pymdownx.superfences
